# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.scenario_parameter import ScenarioParameter  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestScenarioParameter(unittest.TestCase):
    """ScenarioParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ScenarioParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.scenario_parameter.ScenarioParameter()  # noqa: E501
        if include_optional :
            return ScenarioParameter(
                id = 56, 
                parameter = 56, 
                parameter_name = '0', 
                parameter_description = '0', 
                default = True, 
                default_value = '0', 
                values = [
                    1.337
                    ], 
                random = danka_thermal_api.models.random_values.RandomValues(
                    min = 1.337, 
                    max = 1.337, 
                    count = 1, ), 
                normal_dist = danka_thermal_api.models.normal_dist.NormalDist(
                    mean = 1.337, 
                    stddev = 0, 
                    min = 1.337, 
                    max = 1.337, 
                    count = 1, )
            )
        else :
            return ScenarioParameter(
                parameter = 56,
        )

    def testScenarioParameter(self):
        """Test ScenarioParameter"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
