# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import danka_thermal_api
from danka_thermal_api.api.folder_api import FolderApi  # noqa: E501
from danka_thermal_api.rest import ApiException


class TestFolderApi(unittest.TestCase):
    """FolderApi unit test stubs"""

    def setUp(self):
        self.api = danka_thermal_api.api.folder_api.FolderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_folder_create(self):
        """Test case for folder_create

        """
        pass

    def test_folder_delete(self):
        """Test case for folder_delete

        """
        pass

    def test_folder_list(self):
        """Test case for folder_list

        """
        pass

    def test_folder_project_list(self):
        """Test case for folder_project_list

        """
        pass

    def test_folder_project_root_list(self):
        """Test case for folder_project_root_list

        """
        pass

    def test_folder_read(self):
        """Test case for folder_read

        """
        pass

    def test_folder_shared_list(self):
        """Test case for folder_shared_list

        """
        pass

    def test_folder_update(self):
        """Test case for folder_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
