# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.plane_solution import PlaneSolution  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestPlaneSolution(unittest.TestCase):
    """PlaneSolution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlaneSolution
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.plane_solution.PlaneSolution()  # noqa: E501
        if include_optional :
            return PlaneSolution(
                id = 56, 
                timestamp = '0', 
                result = [
                    danka_thermal_api.models._project__projectid__plane_solution__result._project__projectid__plane_solution__result(
                        id = 56, 
                        type = 56, 
                        plane = '0', 
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, 
                        dx = 1.337, 
                        dy = 1.337, 
                        dz = 1.337, 
                        temp = 1.337, )
                    ]
            )
        else :
            return PlaneSolution(
        )

    def testPlaneSolution(self):
        """Test PlaneSolution"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
