# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.pcb_layer import PCBLayer  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestPCBLayer(unittest.TestCase):
    """PCBLayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PCBLayer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.pcb_layer.PCBLayer()  # noqa: E501
        if include_optional :
            return PCBLayer(
                name = '0', 
                thickness = '0', 
                thickness_calc = 1.337, 
                material = 56, 
                material_color = '0', 
                material_name = '0', 
                fill_material = 56, 
                fill_material_color = '0', 
                fill_material_name = '0', 
                ratio = 0, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return PCBLayer(
                name = '0',
                thickness = '0',
                material = 56,
        )

    def testPCBLayer(self):
        """Test PCBLayer"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
