# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.project_task import ProjectTask  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestProjectTask(unittest.TestCase):
    """ProjectTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.project_task.ProjectTask()  # noqa: E501
        if include_optional :
            return ProjectTask(
                id = 56, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                status = '0', 
                user_name = '0', 
                project = 56, 
                project_name = '0', 
                license = '0', 
                instance = '0'
            )
        else :
            return ProjectTask(
                project = 56,
        )

    def testProjectTask(self):
        """Test ProjectTask"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
