# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.transient_source import TransientSource  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestTransientSource(unittest.TestCase):
    """TransientSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransientSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.transient_source.TransientSource()  # noqa: E501
        if include_optional :
            return TransientSource(
                id = 56, 
                name = '0', 
                x = '0', 
                x_calc = 1.337, 
                y = '0', 
                y_calc = 1.337, 
                z = '0', 
                z_calc = 1.337, 
                dx = '0', 
                dx_calc = 1.337, 
                dy = '0', 
                dy_calc = 1.337, 
                dz = '0', 
                dz_calc = 1.337, 
                plane = '0', 
                color = '0', 
                hc = '0', 
                bound = True, 
                index = 0, 
                type = '0', 
                type_id = 56, 
                leaf = True, 
                parent = 56, 
                visible = True, 
                active = True, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                powers = [
                    danka_thermal_api.models.transient_source_power.TransientSourcePower(
                        id = 56, 
                        time = 1.337, 
                        power = '0', 
                        power_calc = 1.337, )
                    ]
            )
        else :
            return TransientSource(
                name = '0',
                x = '0',
                y = '0',
                z = '0',
                dx = '0',
                dy = '0',
                dz = '0',
                plane = '0',
                color = '0',
                index = 0,
                powers = [
                    danka_thermal_api.models.transient_source_power.TransientSourcePower(
                        id = 56, 
                        time = 1.337, 
                        power = '0', 
                        power_calc = 1.337, )
                    ],
        )

    def testTransientSource(self):
        """Test TransientSource"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
