# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.user_license_info_user import UserLicenseInfoUser  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestUserLicenseInfoUser(unittest.TestCase):
    """UserLicenseInfoUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserLicenseInfoUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.user_license_info_user.UserLicenseInfoUser()  # noqa: E501
        if include_optional :
            return UserLicenseInfoUser(
                email = '0', 
                first_name = '0', 
                last_name = '0', 
                thermal_token = '0', 
                groups = [
                    '0'
                    ]
            )
        else :
            return UserLicenseInfoUser(
        )

    def testUserLicenseInfoUser(self):
        """Test UserLicenseInfoUser"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
