# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import danka_thermal_api
from danka_thermal_api.api.home_api import HomeApi  # noqa: E501
from danka_thermal_api.rest import ApiException


class TestHomeApi(unittest.TestCase):
    """HomeApi unit test stubs"""

    def setUp(self):
        self.api = danka_thermal_api.api.home_api.HomeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_home_create(self):
        """Test case for home_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
