# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.task import Task  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Task
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.task.Task()  # noqa: E501
        if include_optional :
            return Task(
                task = '0', 
                status = '0'
            )
        else :
            return Task(
        )

    def testTask(self):
        """Test Task"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
