# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.project import Project  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Project
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.project.Project()  # noqa: E501
        if include_optional :
            return Project(
                id = 56, 
                name = '0', 
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                folder = 56, 
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                world = danka_thermal_api.models.world.World(
                    ambient = 1.337, 
                    resolution = 1.337, 
                    precision = 1.337, 
                    iterations = 0, 
                    lumped = True, 
                    lump_limit = 0, 
                    hc = 1.337, 
                    abs_tol = 1.337, 
                    duration = 1.337, 
                    absolute = True, 
                    dxmin = '0', 
                    dxmax = '0', 
                    dymin = '0', 
                    dymax = '0', 
                    dzmin = '0', 
                    dzmax = '0', 
                    show_grid = True, 
                    show_outline = True, 
                    steps = 1, 
                    save_internal_temp = True, ), 
                thumbnail = '0', 
                owner = True, 
                edit = True, 
                view = True
            )
        else :
            return Project(
                name = '0',
                world = danka_thermal_api.models.world.World(
                    ambient = 1.337, 
                    resolution = 1.337, 
                    precision = 1.337, 
                    iterations = 0, 
                    lumped = True, 
                    lump_limit = 0, 
                    hc = 1.337, 
                    abs_tol = 1.337, 
                    duration = 1.337, 
                    absolute = True, 
                    dxmin = '0', 
                    dxmax = '0', 
                    dymin = '0', 
                    dymax = '0', 
                    dzmin = '0', 
                    dzmax = '0', 
                    show_grid = True, 
                    show_outline = True, 
                    steps = 1, 
                    save_internal_temp = True, ),
        )

    def testProject(self):
        """Test Project"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
