# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.assembly import Assembly  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestAssembly(unittest.TestCase):
    """Assembly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Assembly
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.assembly.Assembly()  # noqa: E501
        if include_optional :
            return Assembly(
                id = 56, 
                name = '0', 
                index = 0, 
                type = '0', 
                leaf = True, 
                children = '0', 
                parent = 56, 
                visible = True, 
                collapsed = True, 
                active = True, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                lumped = True, 
                hc = '0', 
                is_array = True, 
                xcount = '0', 
                ycount = '0', 
                zcount = '0', 
                xpitch = '0', 
                ypitch = '0', 
                zpitch = '0', 
                xcount_calc = 1.337, 
                ycount_calc = 1.337, 
                zcount_calc = 1.337, 
                xpitch_calc = 1.337, 
                ypitch_calc = 1.337, 
                zpitch_calc = 1.337
            )
        else :
            return Assembly(
                name = '0',
                index = 0,
        )

    def testAssembly(self):
        """Test Assembly"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
