# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import danka_thermal_api
from danka_thermal_api.api.tasks_api import TasksApi  # noqa: E501
from danka_thermal_api.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = danka_thermal_api.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
