# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.world import World  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestWorld(unittest.TestCase):
    """World unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test World
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.world.World()  # noqa: E501
        if include_optional :
            return World(
                ambient = 1.337, 
                resolution = 1.337, 
                precision = 1.337, 
                iterations = 0, 
                lumped = True, 
                lump_limit = 0, 
                hc = 1.337, 
                abs_tol = 1.337, 
                duration = 1.337, 
                absolute = True, 
                dxmin = '0', 
                dxmax = '0', 
                dymin = '0', 
                dymax = '0', 
                dzmin = '0', 
                dzmax = '0', 
                show_grid = True, 
                show_outline = True, 
                steps = 1, 
                save_internal_temp = True
            )
        else :
            return World(
        )

    def testWorld(self):
        """Test World"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
