# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import danka_thermal_api
from danka_thermal_api.api.user_api import UserApi  # noqa: E501
from danka_thermal_api.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = danka_thermal_api.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_list(self):
        """Test case for user_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
