# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.plane import Plane  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestPlane(unittest.TestCase):
    """Plane unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Plane
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.plane.Plane()  # noqa: E501
        if include_optional :
            return Plane(
                id = 56, 
                name = '0', 
                type = '0', 
                plane = '0', 
                coordinate = '0', 
                visible = True, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return Plane(
                name = '0',
                plane = '0',
                coordinate = '0',
        )

    def testPlane(self):
        """Test Plane"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
