# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.cylinder import Cylinder  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestCylinder(unittest.TestCase):
    """Cylinder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Cylinder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.cylinder.Cylinder()  # noqa: E501
        if include_optional :
            return Cylinder(
                id = 56, 
                name = '0', 
                x = '0', 
                y = '0', 
                z = '0', 
                dx = '0', 
                dy = '0', 
                dz = '0', 
                x_calc = 1.337, 
                y_calc = 1.337, 
                z_calc = 1.337, 
                dx_calc = 1.337, 
                dy_calc = 1.337, 
                dz_calc = 1.337, 
                plane = '0', 
                power = '0', 
                power_calc = 1.337, 
                material = 56, 
                color = '0', 
                material_name = '0', 
                hc = '0', 
                bound = True, 
                hole = True, 
                index = 0, 
                type = '0', 
                type_id = 56, 
                leaf = True, 
                parent = 56, 
                visible = True, 
                active = True, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return Cylinder(
                name = '0',
                x = '0',
                y = '0',
                z = '0',
                dx = '0',
                dy = '0',
                dz = '0',
                plane = '0',
                material = 56,
                index = 0,
        )

    def testCylinder(self):
        """Test Cylinder"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
