# coding: utf-8

"""
    DANKA THERMAL API

    DANKA THERMAL API  # noqa: E501

    The version of the OpenAPI document: development
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import danka_thermal_api
from danka_thermal_api.models.random_values import RandomValues  # noqa: E501
from danka_thermal_api.rest import ApiException

class TestRandomValues(unittest.TestCase):
    """RandomValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RandomValues
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = danka_thermal_api.models.random_values.RandomValues()  # noqa: E501
        if include_optional :
            return RandomValues(
                min = 1.337, 
                max = 1.337, 
                count = 1
            )
        else :
            return RandomValues(
                min = 1.337,
                max = 1.337,
                count = 1,
        )

    def testRandomValues(self):
        """Test RandomValues"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
