# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tasks_api import TasksApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
