# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.project_material import ProjectMaterial  # noqa: E501
from openapi_client.rest import ApiException

class TestProjectMaterial(unittest.TestCase):
    """ProjectMaterial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectMaterial
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.project_material.ProjectMaterial()  # noqa: E501
        if include_optional :
            return ProjectMaterial(
                id = 56, 
                name = '0', 
                library_name = '0', 
                color = '0', 
                anisotropic = True, 
                conductivity = '0', 
                conductivity_y = '0', 
                conductivity_z = '0', 
                conductivity_calc = 1.337, 
                conductivity_y_calc = 1.337, 
                conductivity_z_calc = 1.337, 
                density = 1.337, 
                specific_heat = 1.337, 
                material = 56, 
                source_material = openapi_client.models.material.Material(
                    id = 56, 
                    library_id = '0', 
                    name = '0', 
                    color = '0', 
                    anisotropic = True, 
                    conductivity = 1.337, 
                    conductivity_y = 1.337, 
                    conductivity_z = 1.337, 
                    density = 1.337, 
                    specific_heat = 1.337, ), 
                used = True
            )
        else :
            return ProjectMaterial(
                name = '0',
                color = '0',
                conductivity = '0',
        )

    def testProjectMaterial(self):
        """Test ProjectMaterial"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
