# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.library_permission import LibraryPermission  # noqa: E501
from openapi_client.rest import ApiException

class TestLibraryPermission(unittest.TestCase):
    """LibraryPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LibraryPermission
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.library_permission.LibraryPermission()  # noqa: E501
        if include_optional :
            return LibraryPermission(
                username = '0', 
                permissions = openapi_client.models._library__libraryid__permissions__permissions._library__libraryid__permissions__permissions(
                    owner = True, 
                    editor = True, 
                    viewer = True, )
            )
        else :
            return LibraryPermission(
        )

    def testLibraryPermission(self):
        """Test LibraryPermission"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
