# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.user_license_info import UserLicenseInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestUserLicenseInfo(unittest.TestCase):
    """UserLicenseInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserLicenseInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.user_license_info.UserLicenseInfo()  # noqa: E501
        if include_optional :
            return UserLicenseInfo(
                user = openapi_client.models.user_license_info_user.UserLicenseInfo_user(
                    email = '0', 
                    first_name = '0', 
                    last_name = '0', 
                    api_token = '0', 
                    groups = [
                        '0'
                        ], ), 
                licenses = [
                    openapi_client.models.user_license_info_licenses.UserLicenseInfo_licenses(
                        feature = '0', 
                        description = '0', 
                        expiration = '0', 
                        group_limit = 56, )
                    ]
            )
        else :
            return UserLicenseInfo(
        )

    def testUserLicenseInfo(self):
        """Test UserLicenseInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
