# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_list(self):
        """Test case for user_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
