# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.material import Material  # noqa: E501
from openapi_client.rest import ApiException

class TestMaterial(unittest.TestCase):
    """Material unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Material
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.material.Material()  # noqa: E501
        if include_optional :
            return Material(
                id = 56, 
                library_id = '0', 
                name = '0', 
                color = '0', 
                anisotropic = True, 
                conductivity = 1.337, 
                conductivity_y = 1.337, 
                conductivity_z = 1.337, 
                density = 1.337, 
                specific_heat = 1.337
            )
        else :
            return Material(
                name = '0',
                color = '0',
                conductivity = 1.337,
                conductivity_y = 1.337,
                conductivity_z = 1.337,
        )

    def testMaterial(self):
        """Test Material"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
