# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.via_array import ViaArray  # noqa: E501
from openapi_client.rest import ApiException

class TestViaArray(unittest.TestCase):
    """ViaArray unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ViaArray
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.via_array.ViaArray()  # noqa: E501
        if include_optional :
            return ViaArray(
                id = 56, 
                name = '0', 
                index = 0, 
                type = '0', 
                type_id = 56, 
                leaf = True, 
                parent = 56, 
                visible = True, 
                active = True, 
                x = '0', 
                y = '0', 
                z = '0', 
                dx = '0', 
                dy = '0', 
                dz = '0', 
                x_calc = 1.337, 
                y_calc = 1.337, 
                z_calc = 1.337, 
                dx_calc = 1.337, 
                dy_calc = 1.337, 
                dz_calc = 1.337, 
                xcount = '0', 
                ycount = '0', 
                xpitch = '0', 
                ypitch = '0', 
                diameter = '0', 
                xcount_calc = 56, 
                ycount_calc = 56, 
                xpitch_calc = 1.337, 
                ypitch_calc = 1.337, 
                diameter_calc = 1.337, 
                material = 56, 
                fill_material = 56, 
                lumped = True, 
                hc = '0', 
                color = '0', 
                fill_color = '0', 
                material_name = '0', 
                fill_material_name = '0', 
                composite_material = [
                    1.337
                    ], 
                is_plated = True, 
                inner_diameter = '0', 
                inner_diameter_calc = 1.337, 
                hole_material = 56, 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return ViaArray(
                name = '0',
                index = 0,
                x = '0',
                y = '0',
                z = '0',
                dx = '0',
                dy = '0',
                dz = '0',
                xcount = '0',
                ycount = '0',
                xpitch = '0',
                ypitch = '0',
                diameter = '0',
                material = 56,
        )

    def testViaArray(self):
        """Test ViaArray"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
