# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.heatsink import Heatsink  # noqa: E501
from openapi_client.rest import ApiException

class TestHeatsink(unittest.TestCase):
    """Heatsink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Heatsink
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.heatsink.Heatsink()  # noqa: E501
        if include_optional :
            return Heatsink(
                id = 56, 
                name = '0', 
                index = 0, 
                type = '0', 
                type_id = 56, 
                leaf = True, 
                parent = 56, 
                visible = True, 
                active = True, 
                material = 56, 
                color = '0', 
                material_name = '0', 
                x = '0', 
                y = '0', 
                z = '0', 
                base_dx = '0', 
                base_dy = '0', 
                base_dz = '0', 
                x_calc = 1.337, 
                y_calc = 1.337, 
                z_calc = 1.337, 
                base_dx_calc = 1.337, 
                base_dy_calc = 1.337, 
                base_dz_calc = 1.337, 
                fin_height = '0', 
                fin_thickness = '0', 
                fin_count = '0', 
                fin_height_calc = 1.337, 
                fin_thickness_calc = 1.337, 
                fin_count_calc = 56, 
                hc = '0', 
                bound = True, 
                fin_axis = '0', 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return Heatsink(
                name = '0',
                index = 0,
                material = 56,
                x = '0',
                y = '0',
                z = '0',
                base_dx = '0',
                base_dy = '0',
                base_dz = '0',
                fin_height = '0',
                fin_thickness = '0',
                fin_count = '0',
                fin_axis = '0',
        )

    def testHeatsink(self):
        """Test Heatsink"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
