# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.pcb import PCB  # noqa: E501
from openapi_client.rest import ApiException

class TestPCB(unittest.TestCase):
    """PCB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PCB
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.pcb.PCB()  # noqa: E501
        if include_optional :
            return PCB(
                id = 56, 
                name = '0', 
                index = 0, 
                type = '0', 
                type_id = 56, 
                leaf = True, 
                parent = 56, 
                visible = True, 
                active = True, 
                x = '0', 
                y = '0', 
                z = '0', 
                dx = '0', 
                dy = '0', 
                dz = 1.337, 
                x_calc = 1.337, 
                y_calc = 1.337, 
                z_calc = 1.337, 
                dx_calc = 1.337, 
                dy_calc = 1.337, 
                dz_calc = 1.337, 
                auto_via = True, 
                hc = '0', 
                layers = [
                    openapi_client.models.pcb_layer.PCBLayer(
                        name = '0', 
                        thickness = '0', 
                        thickness_calc = 1.337, 
                        material = 56, 
                        material_color = '0', 
                        material_name = '0', 
                        fill_material = 56, 
                        fill_material_color = '0', 
                        fill_material_name = '0', 
                        ratio = 0, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ], 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else :
            return PCB(
                name = '0',
                index = 0,
                x = '0',
                y = '0',
                z = '0',
                dx = '0',
                dy = '0',
                layers = [
                    openapi_client.models.pcb_layer.PCBLayer(
                        name = '0', 
                        thickness = '0', 
                        thickness_calc = 1.337, 
                        material = 56, 
                        material_color = '0', 
                        material_name = '0', 
                        fill_material = 56, 
                        fill_material_color = '0', 
                        fill_material_name = '0', 
                        ratio = 0, 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )

    def testPCB(self):
        """Test PCB"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
