# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.task_log import TaskLog  # noqa: E501
from openapi_client.rest import ApiException

class TestTaskLog(unittest.TestCase):
    """TaskLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TaskLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.task_log.TaskLog()  # noqa: E501
        if include_optional :
            return TaskLog(
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                log = '0'
            )
        else :
            return TaskLog(
                log = '0',
        )

    def testTaskLog(self):
        """Test TaskLog"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
