# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.library_api import LibraryApi  # noqa: E501
from openapi_client.rest import ApiException


class TestLibraryApi(unittest.TestCase):
    """LibraryApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.library_api.LibraryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_library_create(self):
        """Test case for library_create

        """
        pass

    def test_library_delete(self):
        """Test case for library_delete

        """
        pass

    def test_library_list(self):
        """Test case for library_list

        """
        pass

    def test_library_material_create(self):
        """Test case for library_material_create

        """
        pass

    def test_library_material_delete(self):
        """Test case for library_material_delete

        """
        pass

    def test_library_material_list(self):
        """Test case for library_material_list

        """
        pass

    def test_library_material_read(self):
        """Test case for library_material_read

        """
        pass

    def test_library_material_update(self):
        """Test case for library_material_update

        """
        pass

    def test_library_permissions_list(self):
        """Test case for library_permissions_list

        """
        pass

    def test_library_permissions_update(self):
        """Test case for library_permissions_update

        """
        pass

    def test_library_read(self):
        """Test case for library_read

        """
        pass

    def test_library_update(self):
        """Test case for library_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
