# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.normal_dist import NormalDist  # noqa: E501
from openapi_client.rest import ApiException

class TestNormalDist(unittest.TestCase):
    """NormalDist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NormalDist
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.normal_dist.NormalDist()  # noqa: E501
        if include_optional :
            return NormalDist(
                mean = 1.337, 
                stddev = 0, 
                min = 1.337, 
                max = 1.337, 
                count = 1
            )
        else :
            return NormalDist(
                mean = 1.337,
                stddev = 0,
                min = 1.337,
                max = 1.337,
                count = 1,
        )

    def testNormalDist(self):
        """Test NormalDist"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
