# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.project_api import ProjectApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_planeid_solution_list(self):
        """Test case for planeid_solution_list

        """
        pass

    def test_project_assembly_clone_create(self):
        """Test case for project_assembly_clone_create

        """
        pass

    def test_project_assembly_create(self):
        """Test case for project_assembly_create

        """
        pass

    def test_project_assembly_delete(self):
        """Test case for project_assembly_delete

        """
        pass

    def test_project_assembly_list(self):
        """Test case for project_assembly_list

        """
        pass

    def test_project_assembly_read(self):
        """Test case for project_assembly_read

        """
        pass

    def test_project_assembly_translate_create(self):
        """Test case for project_assembly_translate_create

        """
        pass

    def test_project_assembly_update(self):
        """Test case for project_assembly_update

        """
        pass

    def test_project_bga_clone_create(self):
        """Test case for project_bga_clone_create

        """
        pass

    def test_project_bga_create(self):
        """Test case for project_bga_create

        """
        pass

    def test_project_bga_delete(self):
        """Test case for project_bga_delete

        """
        pass

    def test_project_bga_delete_all(self):
        """Test case for project_bga_delete_all

        """
        pass

    def test_project_bga_list(self):
        """Test case for project_bga_list

        """
        pass

    def test_project_bga_read(self):
        """Test case for project_bga_read

        """
        pass

    def test_project_bga_update(self):
        """Test case for project_bga_update

        """
        pass

    def test_project_box_clone_create(self):
        """Test case for project_box_clone_create

        """
        pass

    def test_project_box_create(self):
        """Test case for project_box_create

        """
        pass

    def test_project_box_delete(self):
        """Test case for project_box_delete

        """
        pass

    def test_project_box_delete_all(self):
        """Test case for project_box_delete_all

        """
        pass

    def test_project_box_list(self):
        """Test case for project_box_list

        """
        pass

    def test_project_box_read(self):
        """Test case for project_box_read

        """
        pass

    def test_project_box_update(self):
        """Test case for project_box_update

        """
        pass

    def test_project_clone_create(self):
        """Test case for project_clone_create

        """
        pass

    def test_project_create(self):
        """Test case for project_create

        """
        pass

    def test_project_cylinder_clone_create(self):
        """Test case for project_cylinder_clone_create

        """
        pass

    def test_project_cylinder_create(self):
        """Test case for project_cylinder_create

        """
        pass

    def test_project_cylinder_delete(self):
        """Test case for project_cylinder_delete

        """
        pass

    def test_project_cylinder_delete_all(self):
        """Test case for project_cylinder_delete_all

        """
        pass

    def test_project_cylinder_list(self):
        """Test case for project_cylinder_list

        """
        pass

    def test_project_cylinder_read(self):
        """Test case for project_cylinder_read

        """
        pass

    def test_project_cylinder_update(self):
        """Test case for project_cylinder_update

        """
        pass

    def test_project_delete(self):
        """Test case for project_delete

        """
        pass

    def test_project_heatsink_clone_create(self):
        """Test case for project_heatsink_clone_create

        """
        pass

    def test_project_heatsink_create(self):
        """Test case for project_heatsink_create

        """
        pass

    def test_project_heatsink_delete(self):
        """Test case for project_heatsink_delete

        """
        pass

    def test_project_heatsink_delete_all(self):
        """Test case for project_heatsink_delete_all

        """
        pass

    def test_project_heatsink_list(self):
        """Test case for project_heatsink_list

        """
        pass

    def test_project_heatsink_read(self):
        """Test case for project_heatsink_read

        """
        pass

    def test_project_heatsink_update(self):
        """Test case for project_heatsink_update

        """
        pass

    def test_project_json_create(self):
        """Test case for project_json_create

        """
        pass

    def test_project_list(self):
        """Test case for project_list

        """
        pass

    def test_project_log_list(self):
        """Test case for project_log_list

        """
        pass

    def test_project_material_create(self):
        """Test case for project_material_create

        """
        pass

    def test_project_material_delete(self):
        """Test case for project_material_delete

        """
        pass

    def test_project_material_list(self):
        """Test case for project_material_list

        """
        pass

    def test_project_material_read(self):
        """Test case for project_material_read

        """
        pass

    def test_project_material_update(self):
        """Test case for project_material_update

        """
        pass

    def test_project_parameter_create(self):
        """Test case for project_parameter_create

        """
        pass

    def test_project_parameter_delete(self):
        """Test case for project_parameter_delete

        """
        pass

    def test_project_parameter_list(self):
        """Test case for project_parameter_list

        """
        pass

    def test_project_parameter_read(self):
        """Test case for project_parameter_read

        """
        pass

    def test_project_parameter_update(self):
        """Test case for project_parameter_update

        """
        pass

    def test_project_pcb_clone_create(self):
        """Test case for project_pcb_clone_create

        """
        pass

    def test_project_pcb_create(self):
        """Test case for project_pcb_create

        """
        pass

    def test_project_pcb_delete(self):
        """Test case for project_pcb_delete

        """
        pass

    def test_project_pcb_delete_all(self):
        """Test case for project_pcb_delete_all

        """
        pass

    def test_project_pcb_list(self):
        """Test case for project_pcb_list

        """
        pass

    def test_project_pcb_read(self):
        """Test case for project_pcb_read

        """
        pass

    def test_project_pcb_update(self):
        """Test case for project_pcb_update

        """
        pass

    def test_project_permissions_list(self):
        """Test case for project_permissions_list

        """
        pass

    def test_project_permissions_update(self):
        """Test case for project_permissions_update

        """
        pass

    def test_project_plane_create(self):
        """Test case for project_plane_create

        """
        pass

    def test_project_plane_delete(self):
        """Test case for project_plane_delete

        """
        pass

    def test_project_plane_list(self):
        """Test case for project_plane_list

        """
        pass

    def test_project_plane_read(self):
        """Test case for project_plane_read

        """
        pass

    def test_project_plane_solution_list(self):
        """Test case for project_plane_solution_list

        """
        pass

    def test_project_plane_update(self):
        """Test case for project_plane_update

        """
        pass

    def test_project_polygon_clone_create(self):
        """Test case for project_polygon_clone_create

        """
        pass

    def test_project_polygon_create(self):
        """Test case for project_polygon_create

        """
        pass

    def test_project_polygon_delete(self):
        """Test case for project_polygon_delete

        """
        pass

    def test_project_polygon_delete_all(self):
        """Test case for project_polygon_delete_all

        """
        pass

    def test_project_polygon_list(self):
        """Test case for project_polygon_list

        """
        pass

    def test_project_polygon_read(self):
        """Test case for project_polygon_read

        """
        pass

    def test_project_polygon_update(self):
        """Test case for project_polygon_update

        """
        pass

    def test_project_read(self):
        """Test case for project_read

        """
        pass

    def test_project_scenario_case_list(self):
        """Test case for project_scenario_case_list

        """
        pass

    def test_project_scenario_case_plane_solution_list(self):
        """Test case for project_scenario_case_plane_solution_list

        """
        pass

    def test_project_scenario_case_solution_list(self):
        """Test case for project_scenario_case_solution_list

        """
        pass

    def test_project_scenario_create(self):
        """Test case for project_scenario_create

        """
        pass

    def test_project_scenario_delete(self):
        """Test case for project_scenario_delete

        """
        pass

    def test_project_scenario_list(self):
        """Test case for project_scenario_list

        """
        pass

    def test_project_scenario_parameter_list(self):
        """Test case for project_scenario_parameter_list

        """
        pass

    def test_project_scenario_parameter_read(self):
        """Test case for project_scenario_parameter_read

        """
        pass

    def test_project_scenario_parameter_update(self):
        """Test case for project_scenario_parameter_update

        """
        pass

    def test_project_scenario_read(self):
        """Test case for project_scenario_read

        """
        pass

    def test_project_scenario_run_update(self):
        """Test case for project_scenario_run_update

        """
        pass

    def test_project_scenario_task_delete(self):
        """Test case for project_scenario_task_delete

        """
        pass

    def test_project_scenario_task_list(self):
        """Test case for project_scenario_task_list

        """
        pass

    def test_project_scenario_update(self):
        """Test case for project_scenario_update

        """
        pass

    def test_project_solution_list(self):
        """Test case for project_solution_list

        """
        pass

    def test_project_solution_plane_list(self):
        """Test case for project_solution_plane_list

        """
        pass

    def test_project_solve_list(self):
        """Test case for project_solve_list

        """
        pass

    def test_project_source_clone_create(self):
        """Test case for project_source_clone_create

        """
        pass

    def test_project_source_create(self):
        """Test case for project_source_create

        """
        pass

    def test_project_source_delete(self):
        """Test case for project_source_delete

        """
        pass

    def test_project_source_delete_all(self):
        """Test case for project_source_delete_all

        """
        pass

    def test_project_source_list(self):
        """Test case for project_source_list

        """
        pass

    def test_project_source_read(self):
        """Test case for project_source_read

        """
        pass

    def test_project_source_update(self):
        """Test case for project_source_update

        """
        pass

    def test_project_task_delete(self):
        """Test case for project_task_delete

        """
        pass

    def test_project_task_list(self):
        """Test case for project_task_list

        """
        pass

    def test_project_task_read(self):
        """Test case for project_task_read

        """
        pass

    def test_project_thumbnail_update(self):
        """Test case for project_thumbnail_update

        """
        pass

    def test_project_transient_list(self):
        """Test case for project_transient_list

        """
        pass

    def test_project_transient_plane_list(self):
        """Test case for project_transient_plane_list

        """
        pass

    def test_project_transient_read(self):
        """Test case for project_transient_read

        """
        pass

    def test_project_transient_read_0(self):
        """Test case for project_transient_read_0

        """
        pass

    def test_project_tree_list(self):
        """Test case for project_tree_list

        """
        pass

    def test_project_undo_create(self):
        """Test case for project_undo_create

        """
        pass

    def test_project_update(self):
        """Test case for project_update

        """
        pass

    def test_project_via_array_clone_create(self):
        """Test case for project_via_array_clone_create

        """
        pass

    def test_project_via_array_create(self):
        """Test case for project_via_array_create

        """
        pass

    def test_project_via_array_delete(self):
        """Test case for project_via_array_delete

        """
        pass

    def test_project_via_array_delete_all(self):
        """Test case for project_via_array_delete_all

        """
        pass

    def test_project_via_array_list(self):
        """Test case for project_via_array_list

        """
        pass

    def test_project_via_array_read(self):
        """Test case for project_via_array_read

        """
        pass

    def test_project_via_array_update(self):
        """Test case for project_via_array_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
