# coding: utf-8

"""
    ANEMOI API

    ANEMOI API  # noqa: E501

    The version of the OpenAPI document: 2022.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.user_license_info_licenses import UserLicenseInfoLicenses  # noqa: E501
from openapi_client.rest import ApiException

class TestUserLicenseInfoLicenses(unittest.TestCase):
    """UserLicenseInfoLicenses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserLicenseInfoLicenses
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.user_license_info_licenses.UserLicenseInfoLicenses()  # noqa: E501
        if include_optional :
            return UserLicenseInfoLicenses(
                feature = '0', 
                description = '0', 
                expiration = '0', 
                group_limit = 56
            )
        else :
            return UserLicenseInfoLicenses(
        )

    def testUserLicenseInfoLicenses(self):
        """Test UserLicenseInfoLicenses"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
